### PR TITLE
Hopefully this will actually fix it this time...

### PR DESCRIPTION
**Pull request by lilmoefow**
FIXED(maybe)

### CODE REVIEW

**Comment by b0bst3r** [comment]
No cigar :(

**Comment by Sil3ntStorm** [comment]
What's the problem anyway?

**Comment by b0bst3r** [comment]
The problem is Lithium ore and Mekanism's Lithium dust is ore dictionaried to dustLithium.  Which means there are several ways to shortcut several mekanism builds and processes.  It looks like it's not possible to minetweaker out all the shortcuts.

**Comment by Sil3ntStorm** [comment]
May take a look at it tomorrow :)

**Comment by Landrash** [comment]
Assuming they are ore dictionaried couldn't a player just use a storage drawer to convert to the Lithium dust from mekanism assuming they can get one to use as a template?

**Comment by lilmoefow** [comment]
this fix was to remove other mods lithium dust from ore dict. it worked for the most part. but you can now grind nuclearcraft lithium ore into mek lithium dust. which contiunes to break the progression

**Comment by Sil3ntStorm** [comment]
Try #945

**Pull request closed without merging**
