### PR TITLE
Fix Lithium and Brine shortcuts

### PR DESCRIPTION
**Pull request by Sil3ntStorm**
My attempt at fixing Lithium and Brine shortcuts.
Tested this somewhat and haven't found a way to get Lithium Gas without Solar Evaporation Plant.

Sorry about all the other files (aobd.cfg and Mek.sz are the only ones I changed really) but git decided those files had been changed and I couldn't get it to not consider them changed. Maybe something broke the files, dunno.

### CODE REVIEW

**Comment by b0bst3r** [comment]
This is all fixed in BetaJ, thanks for the effort though, seems Nuclearcraft fixed a lot of it and with existing scripts it nails the rest.

**Comment by Sil3ntStorm** [comment]
@b0bst3r ok so let's discuss this here then.
I did craft up to the Elite with these changes while writing the script using ME auto crafting. Haven't noticed any issues.
What kind of problem did you experience with my these changes? You gotta let me know if there are problems, else I cannot possibly fix em ;)

**Comment by b0bst3r** [comment]
In NEI it shows Adv, Elite & Ultimate Induction cell recipes all needing lithium dust when only the initial basic recipe has lithium dust in it.  Same applies for Induction Cells.

The adv+ tiers should not have lithium dust in them but the previous tier cell/provider.

**Comment by b0bst3r** [comment]
Ok yeah so that does seem to work, Not pulled the request because of all the other changes listed, have a look at the commits I did.  Did I miss anything?

**Comment by jimjimjimmyjim** [comment]
it says that it can't update, repeats three times and then freezes and says
server can't keep uo

**Comment by jimjimjimmyjim** [comment]
also core.conf does nothing

**Comment by Sil3ntStorm** [comment]
Looks like you copied them over and those were the only two I changed so yeah looks ok. No longer credited to me now but...

I had it as multiple commits so it's easier to pick what's needed and to be able to undo stuff easier. Also kind of had to have multiples due to the reverts of earlier commits I did. (well I could've squashed those but meh). 

As for the other files, it looks like they may have mixed / wrong / messed up line endings in the repo. git shows the same files as changed when cloning your repo and then instantly doing git status. Like I said I didn't touch those files.

**Comment by Sil3ntStorm** [comment]
@jimjimjimmyjim I guess you meant to comment on #947 ?

**Comment by jimjimjimmyjim** [comment]
yep

**Pull request closed without merging**
